app:
  scheduler:
    enable: true
    interval: 3000
    force-check-delay: 3000

spring:
  application:
    name: scrapper

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

client:
  github:
    base-url: "https://api.github.com"
  stackoverflow:
    base-url: "https://api.stackexchange.com/2.2"
  bot:
    base-url: "http://localhost:8090"

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
