app:
  database-access-type: jpa
  scheduler:
    enable: true
    interval: 60000
    force-check-delay: 60000
  retry:
    type: CONSTANT
    max-attempts: 3
    delay-config:
      constant:
        back-off-period-millis: 1000
      linear:
        initial-interval-millis: 1000
        max-interval-millis: 10000
      exponential:
        initial-interval-millis: 1000
        multiplier: 2.0
        max-interval-millis: 10000
  kafka-config:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    updates-topic:
      name: scrapper.updates
      partitions: 3
      replicas: 3
  use-queue: true


spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 50
      minimum-idle: 20
  liquibase:
    enabled: false
  cache:
    jcache:
      provider: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=60s
    cache-names:
      - rate-limit-buckets-scrapper

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets-scrapper
      url: /.*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - bandwidths:
            - capacity: 100
              time: 1
              unit: minutes
              refill-speed: interval

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

client:
  bot:
    base-url: "http://localhost:8090"
    max-retry-attempts: 3
    retry-delay: 1000
    retry-status-codes:
      - 500
      - 502
      - 503
      - 504

  stackoverflow:
    base-url: "https://api.stackexchange.com/2.2"
    max-retry-attempts: 3
    retry-delay: 1000
    retry-status-codes:
      - 500
      - 502
      - 503
      - 504
  github:
    base-url: "https://api.github.com"
    max-retry-attempts: 3
    retry-delay: 1000
    retry-status-codes:
      - 500
      - 502
      - 503
      - 504


springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
