/*
 * This file is generated by jOOQ.
 */
package edu.java.scrapper.domain.jooq.codegen.tables.pojos;


import java.beans.ConstructorProperties;
import java.io.Serializable;
import java.time.OffsetDateTime;

import javax.annotation.processing.Generated;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.18.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChatLink implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long chatId;
    private Long linkId;
    private OffsetDateTime subscribedAt;

    public ChatLink() {}

    public ChatLink(ChatLink value) {
        this.chatId = value.chatId;
        this.linkId = value.linkId;
        this.subscribedAt = value.subscribedAt;
    }

    @ConstructorProperties({ "chatId", "linkId", "subscribedAt" })
    public ChatLink(
        @NotNull Long chatId,
        @NotNull Long linkId,
        @Nullable OffsetDateTime subscribedAt
    ) {
        this.chatId = chatId;
        this.linkId = linkId;
        this.subscribedAt = subscribedAt;
    }

    /**
     * Getter for <code>CHAT_LINK.CHAT_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getChatId() {
        return this.chatId;
    }

    /**
     * Setter for <code>CHAT_LINK.CHAT_ID</code>.
     */
    public void setChatId(@NotNull Long chatId) {
        this.chatId = chatId;
    }

    /**
     * Getter for <code>CHAT_LINK.LINK_ID</code>.
     */
    @jakarta.validation.constraints.NotNull
    @NotNull
    public Long getLinkId() {
        return this.linkId;
    }

    /**
     * Setter for <code>CHAT_LINK.LINK_ID</code>.
     */
    public void setLinkId(@NotNull Long linkId) {
        this.linkId = linkId;
    }

    /**
     * Getter for <code>CHAT_LINK.SUBSCRIBED_AT</code>.
     */
    @Nullable
    public OffsetDateTime getSubscribedAt() {
        return this.subscribedAt;
    }

    /**
     * Setter for <code>CHAT_LINK.SUBSCRIBED_AT</code>.
     */
    public void setSubscribedAt(@Nullable OffsetDateTime subscribedAt) {
        this.subscribedAt = subscribedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChatLink other = (ChatLink) obj;
        if (this.chatId == null) {
            if (other.chatId != null)
                return false;
        }
        else if (!this.chatId.equals(other.chatId))
            return false;
        if (this.linkId == null) {
            if (other.linkId != null)
                return false;
        }
        else if (!this.linkId.equals(other.linkId))
            return false;
        if (this.subscribedAt == null) {
            if (other.subscribedAt != null)
                return false;
        }
        else if (!this.subscribedAt.equals(other.subscribedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.chatId == null) ? 0 : this.chatId.hashCode());
        result = prime * result + ((this.linkId == null) ? 0 : this.linkId.hashCode());
        result = prime * result + ((this.subscribedAt == null) ? 0 : this.subscribedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChatLink (");

        sb.append(chatId);
        sb.append(", ").append(linkId);
        sb.append(", ").append(subscribedAt);

        sb.append(")");
        return sb.toString();
    }
}
